spring.application.name=ariranha

# Configuração Direta do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoramento_zetta_incendios
spring.datasource.username=postgres
spring.datasource.password=AdminAriranha0321
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de Segurança JWT
ariranha.jwt.secret=ChaveSecretaParaEntrarDoProjetoAriranhaQueMeuGrupoEstaDesenvolvendoComTodosDaEquipe
ariranha.jwt.expiration=86400000