spring.application.name=ariranha
spring.datasource.url=jdbc:postgresql://localhost:5432/monitoramento_zetta_incendios
spring.datasource.username=postgres
spring.datasource.password=admin0321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
ariranha.jwt.secret=ChaveSecretaParaEntrar
ariranha.jwt.expiration=86400000